# permissions for end users to edit maas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: maas-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: maas-operator
    app.kubernetes.io/part-of: maas-operator
    app.kubernetes.io/managed-by: kustomize
  name: maas-editor-role
rules:
- apiGroups:
  - maas.dev.y
  resources:
  - maas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - maas.dev.y
  resources:
  - maas/status
  verbs:
  - get
